# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f04df482457272aad197e1c31cc43debb96cedd1317b4ae772cf63876be9efc0fa79b16813265675a0830a99164f5125e0ac9d8d9ac499fe8e0889f145faf0ad

test:
  secret_key_base: 80f9a7a57738c8ba641acb6f020943e9f53cf9e2ae619b16de4de2e652113a4719d9d5066457ecdc5eebfcbd5b432cd20cba85409e16ae03b3bcc18f5875765e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
